---
  - name : copy hosts file
    copy : src=hosts dest=/etc/hosts

  - name : copy repo file
    copy : src=CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo

  - name : clean yum repo
    shell : yum clean all
